# Generated by Django 5.2.7 on 2025-12-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_description'),
        ('groups', '0002_groupprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(related_name='events', to='groups.groupprofile'),
        ),
    ]
