# Generated by Django 5.2.7 on 2025-12-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_user_role'),
        ('events', '0003_alter_event_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='events', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participant', to='accounts.userprofile'),
        ),
    ]
