# Generated by Django 5.2.7 on 2025-10-22 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="author",
        ),
    ]
