# Generated by Django 5.2.7 on 2025-10-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
