# Generated by Django 5.2.7 on 2025-11-01 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_exp_date_alter_announcement_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='announcements.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published comment date'),
        ),
    ]
