# Generated by Django 5.2.7 on 2025-12-10 21:52

import django_ckeditor_5.fields  # Changed from ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_alter_announcement_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field('Text', config_name='extends'),

        ),
    ]
