# Generated by Django 5.2.7 on 2025-11-22 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="affiliated_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="affiliated_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
