# Generated by Django 5.2.7 on 2025-11-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
